version: '3.8'

services:
  postgres-lite:
    image: postgres:latest
    container_name: postgres-container-lite
    environment:
      POSTGRES_USER: your-username
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-lite:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.05'  # Limit to 0.1 CPU
          memory: 64M  # Limit to 128MB of memory
        reservations:
          cpus: '0.05'  # Reserve 0.05 CPU
          memory: 64M  # Reserve 64MB of memory

  postgres-pro:
    image: postgres:latest
    container_name: postgres-container-pro
    environment:
      POSTGRES_USER: your-username
      POSTGRES_PASSWORD: your-password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"  # Use a different port to avoid conflict
    volumes:
      - postgres-pro:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '2.0'  # Limit to 2 CPUs
          memory: 2G  # Limit to 2GB of memory
        reservations:
          cpus: '2.0'  # Reserve 1 CPU
          memory: 2G  # Reserve 1GB of memory

volumes:
  postgres-lite:
  postgres-pro: