version: "3.9"
services:


#Reads: Approximately 10-50 operations per second
#Writes: Approximately 5-20 operations per second
  postgres:
    image: postgres:12
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 50M

#Reads: Approximately 100-500 operations per second
#Writes: Approximately 50-200 operations per second in theory
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 50M

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro



  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgrespassword@postgres:5432/postgres?sslmode=disable"
    links:
      - postgres
      - prometheus


volumes:
  postgres-data: