version: "3.9"
services:
  postgres:
    image: postgres:12
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 50M
  log-postgres:
    image: postgres:12
    container_name: log-postgres-container
    ports:
      - "5433:5432"
    volumes:
      - log-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: logpassword
      POSTGRES_DB: postgres
    deploy:
      resources:
        limits:
          memory: 1024MB

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 50M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter-container
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres-exporter-container
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgrespassword@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres

volumes:
  postgres-data:
  log-postgres-data:
  grafana-data:
  prometheus-data:
  redis-data:
