global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter-container:9121']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter-container:9187']